### ISSUE TITLE
BOM and POS files

### ISSUE THREAD

**Issue by dudicoco** [Bastardkb/TBK-Mini-PCB-plate#2]
Hi,

First of all, thanks for open sourcing the PCBs!

Is it possible to release BOM and POS files for the diodes so we can use PCB assembly instead of hand soldering them?

**Comment by bstiq** [comment]
Hey,

Thank you for the kind words.
At the moment we don't have BOM and POS files for the PCB.
You should be able to generate them yourself from the Kicad project files.

For the 4x6 and 3x5 PCB I added 0603 footprints instead, as I was afraid the 1206 would be too large to accomodate the curvature when SMT assembled. You might want to modify the project file as well.

It's on my todo list to create an assembly-ready project, but the argos mouse is taking priority right now.

- Q.

**Comment by dudicoco** [comment]
Thanks for the info.
I wonder, why didn't you go the pcb assembly route from the beginning considering that you are using these for production?

**Comment by bstiq** [comment]
At the beginning we were populating all flex PCBs by hand. This was mostly due to time (routing everything and prototyping rounds) and financial constraints (SMD assembly on 0.6mm PCBs is expensive). 
We are still doing so for the 3x6 ones, mostly because we haven't had time to modify them.

**Comment by dudicoco** [comment]
Does that mean that the 3x5 PCBs already have BOM and POS files for SMD assembly?

**Comment by bstiq** [comment]
Yes, see the release section of both of those repositories. 

They are marked as pre-release, but we have been using them with relative success.
The diodes are very small and tend to sometimes detach depending on your manufacturer.
The LEDs work well, just make sure with your manufacturer they're positioning them correctly (facing up/down, GND pin alignment)

**Comment by dudicoco** [comment]
How's the diodes stability when assembled by JLCPCB?
Are there no BOM and POS files for the thumb PCB?

**Comment by bstiq** [comment]
The diodes are mostly fine, every now and then one detaches - either because it moved during reflow or a bump during installation.
This is why there are still 1206 footprints on the PCB, so that you can add one manually if needed.

I'm not sure ordering the PCBs assembled is worth it if you're just going to do a couple builds - PCB assembly on 0.6mm thick black PCBs is expensive, and soldering the diodes manually is a matter of a couple minutes.

At the moment there's no BOM and POS files for the thumb PCBs.
